### ISSUE TITLE
Change `Services` configuration to dictionary

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.AuthorizedServices#16]
I noticed the services configuration/settings are stored as a list:
https://github.com/umbraco/Umbraco.AuthorizedServices/blob/16cfd74f0b669246b5913d2d35b1a36d6485fd63/src/Umbraco.AuthorizedServices/Configuration/AuthorizedServiceSettings.cs#L42

And the `ServiceDetail` should contain a unique service alias:
https://github.com/umbraco/Umbraco.AuthorizedServices/blob/16cfd74f0b669246b5913d2d35b1a36d6485fd63/src/Umbraco.AuthorizedServices/Configuration/AuthorizedServiceSettings.cs#L50-L53

This results in some issues/sub-optimal cases:
- Getting a service by alias uses [SingleOrDefault](https://github.com/umbraco/Umbraco.AuthorizedServices/blob/2d83ffd26f4754cb9276975a69373ad8a71ecc7d/src/Umbraco.AuthorizedServices/Services/Implement/AuthorizedServiceBase.cs#L40), which will always iterate over the whole list to determine whether there's only a single item with that alias and otherwise throw a slightly undescriptive `InvalidOperationException`;
- The configuration binder can't merge the service details by alias (only by index), so you can't easily override environment-specific settings in e.g. `appsettings.Production.json`;
- Configuring services in code requires you to lookup the service in the list or add it to the list if it doesn't exist yet;
- Accessing the details of a specific service requires you to inject `IOptions<AuthorizedServiceSettings>`, which contains all settings and thereby allocates more memory than is strictly needed.

The easy way to fix this is by changing the list to `IDictionary<string, ServiceDetail>` and removing the `Alias`, since that's already specified in the dictionary key.

An even better solution is to use [named options](https://learn.microsoft.com/en-gb/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#named), so you can completely remove the `Services` property from `AuthorizedServiceSettings` (so it only contains the `TokenEncryptionKey`) and use `IOptionsSnapshot<ServiceDetail>` or `IOptionsMonitor<ServiceDetail>` to get a named instance.

Configuring named options is also a lot easier:
```c#
builder.Services.Configure<ServiceDetail>("ServiceAlias", options =>
{
    options.ClientSecret = ""; // Fetch and set client secret
});
```

And the JSON can be easy merged by alias, so the `appsettings.json` can contain:
```json
{
  "Umbraco": {
    "AuthorizedServices": {
      "Services": {
        "ServiceAlias": {
          "DisplayName": "My service",
          "ApiHost": "https://test.api.example.com/"
        }
      }
    }
  }
}
```

And the `appsettings.Production.json` can then easily override a specific setting:
```json
{
  "Umbraco": {
    "AuthorizedServices": {
      "Services": {
        "ServiceAlias": {
          "ApiHost": "https://api.example.com/"
        }
      }
    }
  }
}
```

**Comment by AndyButland** [comment]
The dictionary suggestion makes sense, but I'm not following how we can use named options here.  As the package developer, we don't know what the service aliases will be for a particular solution, so we can't make that registration part of the package.
