### ISSUE TITLE
Auth with ApiKey and header

### ISSUE THREAD

**Issue by mastrup** [umbraco/Umbraco.AuthorizedServices#37]
I have an API endpoint where I need to include more than just my API key.
I need to provide the following headers:
```
x-api-key:{apiKey}
Origin:{originDomain}
```

This is my config in `appSettings.json` for the service:
```json
"danfossLocationApi": {
  "DisplayName": "Danfoss Location API",
  "AuthenticationMethod": "ApiKey",
  "ApiHost": "https://e2e.api.danfoss.com/danfoss-location",
  "ApiKey": "{apiKey}",
  "ApiKeyProvision": {
    "Method": "HttpHeader",
    "Key": "X-Api-Key"
  },
  "SampleRequest": "/countries/DK"
}
```

How would I go about adding the required `Origin` header? Is it supported?

**Comment by AndyButland** [comment]
I guess to be most generic for other services we should add the option to provide further key value pairs in the `ApiKeyProvision` structure, something like:

```
  "ApiKeyProvision": {
    "Method": "HttpHeader",
    "Key": "X-Api-Key"
    "AdditionalParameters": {
        "Origin": "www.myorigin.com"
    }
  },
```

Does that look like it would work for the service you are working with?

**Comment by mastrup** [comment]
Yes, it seems to be a good solution to my problem.

**Comment by AndyButland** [comment]
We've added this configuration option now in version 0.3.1, which is now [available on NuGet](https://www.nuget.org/packages/Umbraco.AuthorizedServices/0.3.1).

**Comment by mastrup** [comment]
Tested and can confirm it works!
Thanks for the quick implementation 🚀

**Comment by AndyButland** [comment]
Glad to hear it's resolved the problem.
