### ISSUE TITLE
Yahoo Authentication

### ISSUE THREAD

**Issue by hassan123-dev** [umbraco/Umbraco.AuthorizedServices#47]
I am running the Umbraco latest code through Visual Studio 
I have installed the "Umbraco.AuthorizedServices" NuGet package.
I have provided the Yahoo configuration as defined in the documentation.
Now I am not able to open the relevant screen.

![image](https://github.com/umbraco/Umbraco.AuthorizedServices/assets/81622533/95ef8472-a745-4e91-af71-0cbef1b3aee2)

![image](https://github.com/umbraco/Umbraco.AuthorizedServices/assets/81622533/1039ec4b-3440-43e7-89af-d7573487969a)

What other steps are required to enable Yahoo authentication?
What Redirect URI should I set in the Yahoo app? 
Where should I declare my redirect URI in the Umbraco app?

**Comment by AndyButland** [comment]
It looks like your configuration isn't quite in the right place - the `AuthorizedServices` section should be a sibling the `CMS` section, not a child.  Please see the example [here](https://docs.umbraco.com/umbraco-dxp/packages/authorized-services#configuring-a-service).

**Comment by hassan123-dev** [comment]
@AndyButland thanks for your help!

![image](https://github.com/umbraco/Umbraco.AuthorizedServices/assets/81622533/a211d0f6-2c79-4017-bf28-07c7baa96e2e)

Now when I click on the authorize service button, it gives an error for an invalid redirect URI.

Can you help me with the following questions?
What Redirect URI should I set in the Yahoo app?
Where should I declare my redirect URI in the Umbraco app?

My target is to set up CMS with Yahoo authentication.

**Comment by hassan123-dev** [comment]
@AndyButland Thanks again for the guidance.

Now I need to follow the [documentation from here](https://docs.umbraco.com/umbraco-cms/reference/security/external-login-providers#generic-examples)to implement Yahoo SSO. Correct?

**Comment by AndyButland** [comment]
I believe so, but I'm not particularly knowledgeable in this area, so it'll probably be best to head to the [Umbraco forums](https://our.umbraco.com/forum/) is you have trouble getting it setup.

I'll close this issue now as the original issue is resolved, and what you are now working on isn't really related to the package.
