### ISSUE TITLE
`package.manifest` not loaded in Umbraco 10

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco.AuthorizedServices#8]
The NuGet package is listed to support both Umbraco 10 and 11, but Umbraco 10 doesn't support virtual `package.manifest` files (eg. from a Razor Class Library), so the package's `index.js` and `style.css` files are not registered, causing the controller not to load properly:

![image](https://github.com/umbraco/Umbraco.AuthorizedServices/assets/3634580/a20d5b7e-e51c-4d1c-9380-2c31618fe3f2)

For my own packages I'm using a manifest filter instead, so ideally this package should do so as well.

**Comment by acoumb** [comment]
Hi @abjerner ,

Thank you for reporting this, it has now been fixed with version [0.1.1](https://www.nuget.org/packages/Umbraco.AuthorizedServices/0.1.1) of the package.

Adrian
